# Enable persistent history
HISTFILE=/commandhistory/.bash_history
HISTSIZE=100000
SAVEHIST=100000

setopt HIST_SAVE_NO_DUPS
setopt INC_APPEND_HISTORY


# Move to directories without cd
setopt autocd

# Initialize completion
autoload -U compinit; compinit

## Aliases
alias l='ls -lah'
alias la='ls -lAh'
alias ll='ls -lh'
alias ls='ls -G'
alias lsa='ls -lah'

alias cc="claude"
alias riskycc="claude --dangerously-skip-permissions"


# Set up fzf key bindings and fuzzy completion
source /usr/share/doc/fzf/examples/key-bindings.zsh
source /usr/share/doc/fzf/examples/completion.zsh

# I like nano for editing
export EDITOR=nano
export VISUAL=nano

export PATH="$HOME/.local/bin:$PATH"

# Source p10k and the custom p10k theme if it exists
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
source ~/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh